api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
#  file:
#    filename: /etc/traefik/traefik_dynamic.yaml
#    watch: true

entryPoints:
  web:
    address: ":80"
#  websecure:
#    address: ":443"
