apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - host: vgolosinu.xyz
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: hw-users-nginx
                port:
                  number: 80
          - path: /books
            pathType: Prefix
            backend:
              service:
                name: hw-books-nginx
                port:
                  number: 80